CREATE TABLE Filme_Series(
    title VARCHAR(10),
    release_year DOUBLE,
    score VARCHAR(10),
    number_of_seasons DOUBLE,
    main_genre VARCHAR(10),
    pais VARCHAR(10),
    filme_serie VARCHAR(10)
    );
INSERT INTO filme_series (title,release_year,score,number_of_seasons,main_genre,País,filme/Série) 
VALUES 
('Breaking Bad',2008,'9.5',5,'drama','Estados Unidos da América','Série'),
 ('Avatar: The Last Airbender',2005,'9.3',3,'scifi','Estados Unidos da América','Série'),
 ('Our Planet',2019,'9.3',1,'documentary','Reino Unido','Série'),
 ('Kota Factory',2019,'9.3',2,'drama','India','Série'),
 ('The Last Dance',2020,'9.1',1,'documentary','Estados Unidos da América','Série'),
 ('Arcane',2021,'9.1',1,'action','Estados Unidos da América','Série'),
 ('Attack on Titan',2013,'9',4,'scifi','Japão','Série'),
 ('Hunter x Hunter',2011,'9',3,'drama','Japão','Série'),
 ('DEATH NOTE',2006,'9',1,'scifi','Japão','Série'),
 ('Seinfeld',1989,'8.9',9,'comedy','Estados Unidos da América','Série'),
 ('Cowboy Bebop',1998,'8.9',1,'western','Japão','Série'),
 ('Heartstopper',2022,'8.9',1,'drama','Reino Unido','Série'),
 ('When They See Us',2019,'8.9',1,'drama','Estados Unidos da América','Série'),
 ('Monty Pythons Flying Circus',1969,'8.8',4,'comedy','Reino Unido','Série'),
 ('BoJack Horseman',2014,'8.8',6,'drama','Estados Unidos da América','Série'),
 ('Chappelles Show',2003,'8.8',3,'comedy','Estados Unidos da América','Série'),
 ('Better Call Saul',2015,'8.8',6,'comedy','Estados Unidos da América','Série'),
 ('Narcos',2015,'8.8',3,'drama','Estados Unidos da América','Série'),
 ('One Piece',1999,'8.8',21,'action','Japão','Série'),
 ('Peaky Blinders',2013,'8.8',6,'drama','Reino Unido','Série'),
 ('Anne with an E',2017,'8.7',3,'drama','Canadá','Série'),
 ('Dark',2017,'8.7',3,'scifi','Alemanha','Série'),
 ('House of Cards',2013,'8.7',6,'drama','Estados Unidos da América','Série'),
 ('Demon Slayer: Kimetsu no Yaiba',2019,'8.7',3,'animation','Japão','Série'),
 ('Stranger Things',2016,'8.7',5,'scifi','Estados Unidos da América','Série'),
 ('One-Punch Man',2015,'8.7',2,'action','Japão','Série'),
 ('The Crown',2016,'8.7',5,'drama','Estados Unidos da América','Série'),
 ('Arrested Development',2003,'8.7',5,'comedy','Estados Unidos da América','Série'),
 ('Friday Night Lights',2006,'8.7',5,'drama','Estados Unidos da América','Série'),
 ('Downton Abbey',2010,'8.7',6,'drama','Reino Unido','Série'),
 ('Code Geass: Lelouch of the Rebellion',2006,'8.7',3,'scifi','Japão','Série'),
 ('Trailer Park Boys',2001,'8.6',12,'comedy','Canadá','Série'),
 ('Mindhunter',2017,'8.6',2,'crime','Estados Unidos da América','Série'),
 ('The Haunting of Hill House',2018,'8.6',1,'drama','Estados Unidos da América','Série'),
 ('The Queens Gambit',2020,'8.6',1,'drama','Estados Unidos da América','Série'),
 ('Cobra Kai',2018,'8.6',5,'action','Estados Unidos da América','Série'),
 ('Wentworth',2013,'8.6',9,'drama','Austrália','Série'),
 ('Its Okay to Not Be Okay',2020,'8.6',1,'drama','República da Coréia','Série'),
 ('Making a Murderer',2015,'8.6',2,'crime','Estados Unidos da América','Série'),
 ('Shameless',2011,'8.6',11,'drama','Estados Unidos da América','Série'),
 ('Sacred Games',2018,'8.6',2,'action','India','Série'),
 ('Formula 1: Drive to Survive',2019,'8.6',6,'documentary','Reino Unido','Série'),
 ('Queer Eye',2018,'8.5',6,'reality','Estados Unidos da América','Série'),
 ('Community',2009,'8.5',6,'comedy','Estados Unidos da América','Série'),
 ('The Last Kingdom',2015,'8.5',5,'action','Reino Unido','Série'),
 ('Schitts Creek',2015,'8.5',6,'comedy','Canadá','Série'),
 ('Neon Genesis Evangelion',1995,'8.5',1,'scifi','Japão','Série'),
 ('Call the Midwife',2012,'8.5',11,'drama','Reino Unido','Série'),
 ('The IT Crowd',2006,'8.5',5,'comedy','Reino Unido','Série'),
 ('ERASED',2016,'8.5',1,'drama','Japão','Série'),
 ('Supernatural',2005,'8.5',15,'scifi','Estados Unidos da América','Série'),
 ('Ozark',2017,'8.5',4,'crime','Estados Unidos da América','Série'),
 ('Delhi Crime',2019,'8.5',1,'drama','India','Série'),
 ('After Life',2019,'8.5',3,'comedy','Reino Unido','Série'),
 ('Hilda',2018,'8.5',2,'scifi','Reino Unido','Série'),
 ('Borgen',2010,'8.5',4,'drama','Dinamarca','Série'),
 ('Ash vs Evil Dead',2015,'8.4',3,'action','Estados Unidos da América','Série'),
 ('Heartland',2007,'8.4',15,'drama','Canadá','Série'),
 ('Unbelievable',2019,'8.4',1,'drama','Estados Unidos da América','Série'),
 ('The Promised Neverland',2019,'8.4',2,'scifi','Japão','Série'),
 ('Derry Girls',2018,'8.4',3,'comedy','Reino Unido','Série'),
 ('Innocent',2017,'8.4',1,'drama','Turquia','Série'),
 ('Trollhunters: Tales of Arcadia',2016,'8.4',3,'action','Estados Unidos da América','Série'),
 ('Outlander',2014,'8.4',6,'scifi','Estados Unidos da América','Série'),
 ('The Legend of Korra',2012,'8.4',4,'action','Estados Unidos da América','Série'),
 ('The Dark Crystal: Age of Resistance',2019,'8.4',1,'scifi','Reino Unido','Série'),
 ('Vincenzo',2021,'8.4',1,'action','República da Coréia','Série'),
 ('Top Boy',2011,'8.4',2,'drama','Reino Unido','Série'),
 ('Babylon Berlin',2017,'8.4',4,'crime','Alemanha','Série'),
 ('Stargate SG-1',1997,'8.4',10,'scifi','Estados Unidos da América','Série'),
 ('Violet Evergarden',2018,'8.4',1,'drama','Japão','Série'),
 ('Narcos: Mexico',2018,'8.4',3,'drama','Estados Unidos da América','Série'),
 ('The Dragon Prince',2018,'8.4',3,'scifi','Estados Unidos da América','Série'),
 ('Maid',2021,'8.4',1,'drama','Estados Unidos da América','Série'),
 ('Car Masters: Rust to Riches',2018,'8.4',3,'reality','Estados Unidos da América','Série'),
 ('Naruto',2002,'8.4',6,'scifi','Japão','Série'),
 ('The Originals',2013,'8.3',5,'scifi','Estados Unidos da América','Série'),
 ('Fauda',2015,'8.3',3,'war','Israel','Série'),
 ('Sex Education',2019,'8.3',4,'drama','Reino Unido','Série'),
 ('Kingdom',2019,'8.3',2,'action','República da Coréia','Série'),
 ('Money Heist',2017,'8.3',5,'crime','Espanha','Série'),
 ('Young Royals',2021,'8.3',1,'drama','Suécia','Série'),
 ('Atypical',2017,'8.3',4,'comedy','Estados Unidos da América','Série'),
 ('Gurren Lagann',2007,'8.3',1,'scifi','Japão','Série'),
 ('30 Rock',2006,'8.3',7,'comedy','Estados Unidos da América','Série'),
 ('Castlevania',2017,'8.3',4,'scifi','Estados Unidos da América','Série'),
 ('Kims Convenience',2016,'8.3',5,'comedy','Canadá','Série'),
 ('Master of None',2015,'8.3',3,'drama','Estados Unidos da América','Série'),
 ('Longmire',2012,'8.3',6,'western','Estados Unidos da América','Série'),
 ('Call My Agent!',2015,'8.3',4,'comedy','França','Série'),
 ('The Get Down',2016,'8.2',2,'drama','Estados Unidos da América','Série'),
 ('Sense8',2015,'8.2',2,'scifi','Estados Unidos da América','Série'),
 ('One Day at a Time',2017,'8.2',4,'comedy','Estados Unidos da América','Série'),
 ('The Kominsky Method',2018,'8.2',3,'drama','Estados Unidos da América','Série'),
 ('Itaewon Class',2020,'8.2',1,'drama','República da Coréia','Série'),
 ('The Good Place',2016,'8.2',4,'scifi','Estados Unidos da América','Série'),
 ('Grace and Frankie',2015,'8.2',7,'comedy','Estados Unidos da América','Série'),
 ('The Witcher',2019,'8.2',2,'scifi','Estados Unidos da América','Série'),
 ('Locked Up',2015,'8.2',4,'drama','Espanha','Série'),
 ('Gilmore Girls',2000,'8.2',8,'comedy','Estados Unidos da América','Série'),
 ('Caliphate',2020,'8.2',1,'war','Suécia','Série'),
 ('Fate/Zero',2011,'8.2',2,'scifi','Japão','Série'),
 ('The Walking Dead',2010,'8.2',11,'action','Estados Unidos da América','Série'),
 ('anohana: The Flower We Saw That Day',2011,'8.2',1,'drama','Japão','Série'),
 ('The Trials of Gabriel Fernandez',2020,'8.1',1,'crime','Estados Unidos da América','Série'),
 ('How to Get Away with Murder',2014,'8.1',6,'drama','Estados Unidos da América','Série'),
 ('Derek',2013,'8.1',3,'drama','Reino Unido','Série'),
 ('Rascal Does Not Dream of Bunny Girl Senpai',2018,'8.1',1,'animation','Japão','Série'),
 ('Wild Wild Country',2018,'8.1',1,'crime','Estados Unidos da América','Série'),
 ('Bodyguard',2018,'8.1',2,'war','Reino Unido','Série'),
 ('American Vandal',2017,'8.1',2,'comedy','Estados Unidos da América','Série'),
 ('The End of the F***ing World',2017,'8.1',2,'crime','Reino Unido','Série'),
 ('Manhunt',2017,'8.1',2,'documentary','Estados Unidos da América','Série'),
 ('Criminal Minds',2005,'8.1',15,'thriller','Estados Unidos da América','Série'),
 ('HAPPY!',2017,'8.1',2,'scifi','Estados Unidos da América','Série'),
 ('Orange Is the New Black',2013,'8.1',7,'drama','Estados Unidos da América','Série'),
 ('Star Trek: Deep Space Nine',1993,'8.1',7,'scifi','Estados Unidos da América','Série'),
 ('Lovesick',2014,'8.1',3,'comedy','Reino Unido','Série'),
 ('Lucifer',2016,'8.1',6,'scifi','Estados Unidos da América','Série'),
 ('F is for Family',2015,'8',5,'comedy','Estados Unidos da América','Série'),
 ('Dont F**k with Cats: Hunting an Internet Killer',2019,'8',1,'crime','Estados Unidos da América','Série'),
 ('GLOW',2017,'8',4,'drama','Estados Unidos da América','Série'),
 ('The Umbrella Academy',2019,'8',3,'comedy','Estados Unidos da América','Série'),
 ('Tabula Rasa',2017,'8',1,'drama','Bélgica','Série'),
 ('Dead to Me',2019,'8',2,'drama','Estados Unidos da América','Série'),
 ('The Mechanism',2018,'8',2,'drama','Brasil','Série'),
 ('Squid Game',2021,'8',2,'action','República da Coréia','Série'),
 ('Toradora!',2008,'8',2,'animation','Japão','Série'),
 ('Comedians in Cars Getting Coffee',2012,'8',11,'comedy','Estados Unidos da América','Série'),
 ('Marco Polo',2014,'8',2,'action','Estados Unidos da América','Série'),
 ('Travelers',2016,'8',3,'scifi','Canadá','Série'),
 ('The Blacklist',2013,'8',9,'drama','Estados Unidos da América','Série'),
 ('Unorthodox',2020,'8',1,'drama','Alemanha','Série'),
 ('Inside Bills Brain: Decoding Bill Gates',2019,'7.9',1,'documentary','Estados Unidos da América','Série'),
 ('On My Block',2018,'7.9',4,'comedy','Estados Unidos da América','Série'),
 ('Medici: Masters of Florence',2016,'7.9',3,'war','Reino Unido','Série'),
 ('The Seven Deadly Sins',2014,'7.9',5,'action','Japão','Série'),
 ('Queen of the South',2016,'7.9',5,'drama','Estados Unidos da América','Série'),
 ('KILL la KILL',2013,'7.9',1,'action','Japão','Série'),
 ('Bloodline',2015,'7.9',3,'drama','Estados Unidos da América','Série'),
 ('Into the Badlands',2015,'7.9',3,'action','Estados Unidos da América','Série'),
 ('Merlin',2008,'7.9',5,'action','Reino Unido','Série'),
 ('InuYasha',2000,'7.9',9,'action','Japão','Série'),
 ('Altered Carbon',2018,'7.9',2,'scifi','Estados Unidos da América','Série'),
 ('The OA',2016,'7.9',2,'scifi','Estados Unidos da América','Série'),
 ('Resurrection: Ertugrul',2014,'7.9',5,'war','Turquia','Série'),
 ('The Borgias',2011,'7.9',3,'drama','Canadá','Série'),
 ('Lilyhammer',2012,'7.9',3,'crime','Noruega','Série'),
 ('Boys Over Flowers',2009,'7.9',1,'comedy','República da Coréia','Série'),
 ('I Think You Should Leave with Tim Robinson',2019,'7.9',3,'comedy','Estados Unidos da América','Série'),
 ('Suburra: Blood on Rome',2017,'7.9',3,'crime','Itália','Série'),
 ('The Sinner',2017,'7.9',4,'crime','Estados Unidos da América','Série'),
 ('The Spy',2019,'7.9',1,'drama','França','Série'),
 ('Santa Clarita Diet',2017,'7.9',3,'comedy','Estados Unidos da América','Série'),
 ('How to Sell Drugs Online (Fast)',2019,'7.9',3,'drama','Alemanha','Série'),
 ('Rise of Empires: Ottoman',2020,'7.9',2,'documentary','Turquia','Série'),
 ('Big Mouth',2017,'7.9',6,'animation','Estados Unidos da América','Série'),
 ('Versailles',2015,'7.9',3,'drama','Canadá','Série'),
 ('She-Ra and the Princesses of Power',2018,'7.8',5,'scifi','Estados Unidos da América','Série'),
 ('A Series of Unfortunate Events',2017,'7.8',3,'action','Estados Unidos da América','Série'),
 ('Gotham',2014,'7.8',5,'scifi','Estados Unidos da América','Série'),
 ('Workin' 'Moms',2017,'7.8',6,'comedy','Canadá','Série'),
 ('Russian Doll',2019,'7.8',2,'drama','Estados Unidos da América','Série'),
 ('Sweet Tooth',2021,'7.8',2,'scifi','Estados Unidos da América','Série'),
 ('Imposters',2017,'7.8',2,'drama','Estados Unidos da América','Série'),
 ('iZombie',2015,'7.8',5,'scifi','Estados Unidos da América','Série'),
 ('Conversations with a Killer: The Ted Bundy Tapes',2019,'7.8',1,'crime','Estados Unidos da América','Série'),
 ('Never Have I Ever',2020,'7.8',4,'drama','Estados Unidos da América','Série'),
 ('My Name',2021,'7.8',1,'thriller','República da Coréia','Série'),
 ('Happy Endings',2011,'7.8',3,'comedy','Estados Unidos da América','Série'),
 ('Crazy Ex-Girlfriend',2015,'7.8',4,'comedy','Estados Unidos da América','Série'),
 ('El Chapo',2017,'7.8',3,'drama','Estados Unidos da América','Série'),
 ('NCIS',2003,'7.8',19,'action','Estados Unidos da América','Série'),
 ('Jane the Virgin',2014,'7.8',5,'drama','Estados Unidos da América','Série'),
 ('Undercover',2019,'7.8',3,'drama','Bélgica','Série'),
 ('DOTA: Dragons Blood',2021,'7.8',2,'scifi','Estados Unidos da América','Série'),
 ('The Innocent',2021,'7.8',1,'crime','Espanha','Série'),
 ('The Staircase',2004,'7.8',2,'crime','França','Série'),
 ('Giri/Haji',2019,'7.8',1,'thriller','Reino Unido','Série'),
 ('Angel Beats!',2010,'7.7',1,'scifi','Japão','Série'),
 ('Love',2016,'7.7',3,'drama','Estados Unidos da América','Série'),
 ('In the Dark',2019,'7.7',4,'comedy','Estados Unidos da América','Série'),
 ('Midnight Mass',2021,'7.7',1,'action','Estados Unidos da América','Série'),
 ('The Vampire Diaries',2009,'7.7',8,'scifi','Estados Unidos da América','Série'),
 ('Alias Grace',2017,'7.7',1,'drama','Canadá','Série'),
 ('You',2018,'7.7',3,'thriller','Estados Unidos da América','Série'),
 ('Norsemen',2016,'7.7',3,'comedy','Noruega','Série'),
 ('Good Girls',2018,'7.7',4,'comedy','Estados Unidos da América','Série'),
 ('Seven Seconds',2018,'7.7',1,'crime','Estados Unidos da América','Série'),
 ('The Chestnut Man',2021,'7.7',1,'crime','Dinamarca','Série'),
 ('Crashing',2016,'7.7',1,'comedy','Reino Unido','Série'),
 ('Maniac',2018,'7.7',1,'drama','Estados Unidos da América','Série'),
 ('New Girl',2011,'7.7',7,'comedy','Estados Unidos da América','Série'),
 ('Miraculous: Tales of Ladybug &amp, Cat Noir',2015,'7.7',4,'romance','França','Série'),
 ('Home for Christmas',2019,'7.7',2,'comedy','Noruega','Série'),
 ('Inside Job',2021,'7.6',1,'comedy','Estados Unidos da América','Série'),
 ('The Serpent',2021,'7.6',1,'drama','Reino Unido','Série'),
 ('Alice in Borderland',2020,'7.6',2,'action','Japão','Série'),
 ('Spinning Out',2020,'7.6',1,'drama','Estados Unidos da América','Série'),
 ('Messiah',2020,'7.6',1,'drama','Estados Unidos da América','Série'),
 ('Teenage Bounty Hunters',2020,'7.6',1,'action','Estados Unidos da América','Série'),
 ('Shadow and Bone',2021,'7.6',1,'scifi','Estados Unidos da América','Série'),
 ('The Devil Next Door',2019,'7.6',1,'documentary','Estados Unidos da América','Série'),
 ('My Little Pony: Friendship Is Magic',2010,'7.6',9,'scifi','Canadá','Série'),
 ('The Magicians',2015,'7.6',5,'drama','Estados Unidos da América','Série'),
 ('Bordertown',2016,'7.6',3,'drama','Finlândia','Série'),
 ('Unbreakable Kimmy Schmidt',2015,'7.6',4,'comedy','Estados Unidos da América','Série'),
 ('Chicago Med',2015,'7.6',8,'drama','Estados Unidos da América','Série'),
 ('The 100',2014,'7.6',7,'drama','Estados Unidos da América','Série'),
 ('The Flash',2014,'7.6',8,'scifi','Estados Unidos da América','Série'),
 ('Cable Girls',2017,'7.6',5,'drama','Espanha','Série'),
 ('Criminal: UK',2019,'7.6',2,'drama','Reino Unido','Série'),
 ('Devilman Crybaby',2018,'7.6',1,'scifi','Japão','Série'),
 ('Madam Secretary',2014,'7.6',6,'war','Estados Unidos da América','Série'),
 ('Sword Art Online',2012,'7.6',4,'scifi','Japão','Série'),
 ('Gilmore Girls: A Year in the Life',2016,'7.6',1,'comedy','Estados Unidos da América','Série'),
 ('Dead Set',2008,'7.6',1,'scifi','Reino Unido','Série'),
 ('Greys Anatomy',2005,'7.6',18,'drama','Estados Unidos da América','Série'),
 ('Goosebumps',1995,'7.6',4,'scifi','Canadá','Série'),
 ('Love 101',2020,'7.5',2,'comedy','Turquia','Série'),
 ('Shooter',2016,'7.5',3,'war','Estados Unidos da América','Série'),
 ('Reign',2013,'7.5',4,'drama','Estados Unidos da América','Série'),
 ('Blue Exorcist',2011,'7.5',2,'scifi','Japão','Série'),
 ('Outer Banks',2020,'7.5',2,'action','Estados Unidos da América','Série'),
 ('Arrow',2012,'7.5',8,'action','Estados Unidos da América','Série'),
 ('Halston',2021,'7.5',1,'drama','Estados Unidos da América','Série'),
 ('The Night Shift',2014,'7.5',4,'drama','Estados Unidos da América','Série'),
 ('The Heirs',2013,'7.5',1,'drama','República da Coréia','Série'),
 ('The Politician',2019,'7.5',2,'comedy','Estados Unidos da América','Série'),
 ('Ragnarok',2020,'7.5',2,'action','Noruega','Série'),
 ('Everything Sucks!',2018,'7.5',1,'drama','Estados Unidos da América','Série'),
 ('Frequency',2016,'7.5',3,'scifi','Estados Unidos da América','Série'),
 ('Dark Matter',2015,'7.5',3,'scifi','Canadá','Série'),
 ('Night Stalker: The Hunt for a Serial Killer',2021,'7.5',1,'crime','Estados Unidos da América','Série'),
 ('Dash &amp, Lily',2020,'7.5',1,'comedy','Estados Unidos da América','Série'),
 ('True Story',2021,'7.5',1,'drama','Estados Unidos da América','Série'),
 ('Hollywood',2020,'7.5',1,'drama','Estados Unidos da América','Série'),
 ('Designated Survivor',2016,'7.5',3,'war','Estados Unidos da América','Série'),
 ('Quicksand',2019,'7.5',1,'drama','Suécia','Série'),
 ('Feel Good',2020,'7.5',2,'drama','Reino Unido','Série'),
 ('Dogs of Berlin',2018,'7.5',1,'drama','Alemanha','Série'),
 ('Evil Genius',2018,'7.5',1,'crime','Estados Unidos da América','Série'),
 ('13 Reasons Why',2017,'7.5',4,'drama','Estados Unidos da América','Série'),
 ('Lupin',2021,'7.5',3,'crime','França','Série'),
 ('All of Us Are Dead',2022,'7.5',1,'action','República da Coréia','Série'),
 ('I Am Not Okay with This',2020,'7.5',1,'comedy','Estados Unidos da América','Serie'),
 ('David Attenborough: A Life on Our Planet',2020,'9',0,'documentary','Reino Unido','Filme'),
 ('Inception',2010,'8.8',0,'scifi','Reino Unido','Filme'),
 ('Forrest Gump',1994,'8.8',0,'drama','Estados Unidos da América','Filme'),
 ('Anbe Sivam',2003,'8.7',0,'comedy','India','Filme'),
 ('Bo Burnham: Inside',2021,'8.7',0,'comedy','Estados Unidos da América','Filme'),
 ('Saving Private Ryan',1998,'8.6',0,'drama','Estados Unidos da América','Filme'),
 ('Django Unchained',2012,'8.4',0,'western','Estados Unidos da América','Filme'),
 ('Dangal',2016,'8.4',0,'action','India','Filme'),
 ('Bo Burnham: Make Happy',2016,'8.4',0,'comedy','Estados Unidos da América','Filme'),
 ('Louis C.K.: Hilarious',2010,'8.4',0,'comedy','Estados Unidos da América','Filme'),
 ('Dave Chappelle: Sticks &amp, Stones',2019,'8.4',0,'comedy','Estados Unidos da América','Filme'),
 ('3 Idiots',2009,'8.4',0,'comedy','India','Filme'),
 ('Black Friday',2004,'8.4',0,'crime','India','Filme'),
 ('Super Deluxe',2019,'8.4',0,'thriller','India','Filme'),
 ('Winter on Fire: Ukraines Fight for Freedom',2015,'8.3',0,'documentary','Ucrânia','Filme'),
 ('Once Upon a Time in America',1984,'8.3',0,'drama','Estados Unidos da América','Filme'),
 ('Taxi Driver',1976,'8.3',0,'crime','Estados Unidos da América','Filme'),
 ('Like Stars on Earth',2007,'8.3',0,'drama','India','Filme'),
 ('Bo Burnham: What.',2013,'8.3',0,'comedy','Estados Unidos da América','Filme'),
 ('Full Metal Jacket',1987,'8.3',0,'drama','Reino Unido','Filme'),
 ('Warrior',2011,'8.2',0,'drama','Estados Unidos da América','Filme'),
 ('Drishyam',2015,'8.2',0,'thriller','India','Filme'),
 ('Queen',2014,'8.2',0,'drama','India','Filme'),
 ('Paan Singh Tomar',2012,'8.2',0,'drama','India','Filme'),
 ('Cowspiracy: The Sustainability Secret',2014,'8.2',0,'documentary','Estados Unidos da América','Filme'),
 ('Virunga',2014,'8.2',0,'war','República Dem. Do Congo','Filme'),
 ('PK',2014,'8.2',0,'comedy','India','Filme'),
 ('BÄhubali 2: The Conclusion',2017,'8.2',0,'fantasy','India','Filme'),
 ('Monty Python and the Holy Grail',1975,'8.2',0,'comedy','Reino Unido','Filme'),
 ('Article 15',2019,'8.2',0,'crime','India','Filme'),
 ('Miracle in Cell No. 7',2019,'8.2',0,'drama','Turquia','Filme'),
 ('13th',2016,'8.2',0,'documentary','Estados Unidos da América','Filme'),
 ('Andhadhun',2018,'8.2',0,'thriller','India','Filme'),
 ('Bill Burr: Paper Tiger',2019,'8.1',0,'comedy','Reino Unido','Filme'),
 ('Udaan',2010,'8.1',0,'drama','India','Filme'),
 ('How to Train Your Dragon',2010,'8.1',0,'fantasy','Estados Unidos da América','Filme'),
 ('Klaus',2019,'8.1',0,'comedy','Espanha','Filme'),
 ('Swades',2004,'8.1',0,'drama','India','Filme'),
 ('Minnal Murali',2021,'8.1',0,'action','India','Filme'),
 ('Rang De Basanti',2006,'8.1',0,'comedy','India','Filme'),
 ('Seaspiracy',2021,'8.1',0,'documentary','Estados Unidos da América','Filme'),
 ('Rush',2013,'8.1',0,'drama','Estados Unidos da América','Filme'),
 ('Hannah Gadsby: Nanette',2018,'8.1',0,'comedy','Austrália','Filme'),
 ('Barfi!',2012,'8.1',0,'drama','India','Filme'),
 ('Haider',2014,'8.1',0,'drama','India','Filme'),
 ('Zindagi Na Milegi Dobara',2011,'8.1',0,'comedy','India','Filme'),
 ('A Silent Voice: The Movie',2016,'8.1',0,'romance','Japão','Filme'),
 ('OMG: Oh My God!',2012,'8.1',0,'fantasy','India','Filme'),
 ('Talvar',2015,'8.1',0,'thriller','India','Filme'),
 ('Into the Wild',2007,'8.1',0,'drama','Estados Unidos da América','Filme'),
 ('Lagaan: Once Upon a Time in India',2001,'8.1',0,'drama','India','Filme'),
 ('My Octopus Teacher',2020,'8.1',0,'documentary','Africa do Sul','Filme'),
 ('Dil Chahta Hai',2001,'8.1',0,'drama','India','Filme'),
 ('Mersal',2017,'8.1',0,'thriller','India','Filme'),
 ('The Legend of Bhagat Singh',2002,'8.1',0,'drama','India','Filme'),
 ('Stand by Me',1986,'8.1',0,'drama','Estados Unidos da América','Filme'),
 ('The Exorcist',1973,'8.1',0,'horror','Estados Unidos da América','Filme'),
 ('Bombay',1995,'8.1',0,'romance','India','Filme'),
 ('Dasvi',2022,'8',0,'drama','India','Filme'),
 ('G.O.R.A.',2004,'8',0,'scifi','Turquia','Filme'),
 ('Blood Diamond',2006,'8',0,'thriller','Estados Unidos da América','Filme'),
 ('Vizontele',2001,'8',0,'comedy','Turquia','Filme'),
 ('Ip Man',2008,'8',0,'drama','Hong-Kong','Filme'),
 ('Her',2013,'8',0,'drama','Estados Unidos da América','Filme'),
 ('The Bourne Ultimatum',2007,'8',0,'thriller','Alemanha','Filme'),
 ('Casino Royale',2006,'8',0,'thriller','Reino Unido','Filme'),
 ('Special 26',2013,'8',0,'thriller','India','Filme'),
 ('Neon Genesis Evangelion: The End of Evangelion',1997,'8',0,'scifi','Japão','Filme'),
 ('BÄhubali: The Beginning',2015,'8',0,'drama','India','Filme'),
 ('Ankhon Dekhi',2014,'8',0,'drama','India','Filme'),
 ('Big Fish',2003,'8',0,'drama','Estados Unidos da América','Filme'),
 ('Silenced',2011,'8',0,'drama','República da Coréia','Filme'),
 ('Life of Brian',1979,'8',0,'comedy','Reino Unido','Filme'),
 ('The Invisible Guest',2017,'8',0,'thriller','Espanha','Filme'),
 ('Dave Chappelle: The Closer',2021,'8',0,'comedy','Estados Unidos da América','Filme'),
 ('Blade Runner 2049',2017,'8',0,'scifi','Canadá','Filme'),
 ('The Imitation Game',2014,'8',0,'thriller','Estados Unidos da América','Filme'),
 ('Jab We Met',2007,'7.9',0,'comedy','India','Filme'),
 ('Free to Play',2014,'7.9',0,'documentary','Ucrânia','Filme'),
 ('Monty Python Live at the Hollywood Bowl',1982,'7.9',0,'comedy','Reino Unido','Filme'),
 ('Dev.D',2009,'7.9',0,'drama','India','Filme'),
 ('Marriage Story',2019,'7.9',0,'drama','Reino Unido','Filme'),
 ('Icarus',2017,'7.9',0,'documentary','Estados Unidos da América','Filme'),
 ('I Am Not Your Negro',2017,'7.9',0,'documentary','Bélgica','Filme'),
 ('Ricky Gervais: Humanity',2018,'7.9',0,'comedy','Reino Unido','Filme'),
 ('Secret Superstar',2017,'7.9',0,'drama','India','Filme'),
 ('Kal Ho Naa Ho',2003,'7.9',0,'drama','India','Filme'),
 ('Pad Man',2018,'7.9',0,'comedy','India','Filme'),
 ('Shyam Singha Roy',2021,'7.9',0,'drama','India','Filme'),
 ('How to Train Your Dragon 2',2014,'7.8',0,'fantasy','Estados Unidos da América','Filme'),
 ('The Irishman',2019,'7.8',0,'drama','Estados Unidos da América','Filme'),
 ('Gangaajal',2003,'7.8',0,'drama','India','Filme'),
 ('The Girl with the Dragon Tattoo',2011,'7.8',0,'crime','Noruega','Filme'),
 ('Lakshya',2004,'7.8',0,'drama','India','Filme'),
 ('The Social Network',2010,'7.8',0,'drama','Estados Unidos da América','Filme'),
 ('Dunkirk',2017,'7.8',0,'drama','Estados Unidos da América','Filme'),
 ('Kai Po Che!',2013,'7.8',0,'drama','India','Filme'),
 ('The Gentlemen',2019,'7.8',0,'comedy','Estados Unidos da América','Filme'),
 ('Marco Polo: One Hundred Eyes',2015,'7.8',0,'action','Estados Unidos da América','Filme'),
 ('The Hateful Eight',2015,'7.8',0,'western','Estados Unidos da América','Filme'),
 ('Hunt for the Wilderpeople',2016,'7.8',0,'comedy','Nova Zelândia','Filme'),
 ('The Last Samurai',2003,'7.8',0,'drama','Nova Zelândia','Filme'),
 ('Gattaca',1997,'7.8',0,'thriller','Estados Unidos da América','Filme'),
 ('The Butterflys Dream',2013,'7.8',0,'drama','Turquia','Filme'),
 ('14 Peaks: Nothing Is Impossible',2021,'7.8',0,'documentary','Estados Unidos da América','Filme'),
 ('Nightcrawler',2014,'7.8',0,'crime','Estados Unidos da América','Filme'),
 ('Udta Punjab',2016,'7.8',0,'crime','India','Filme'),
 ('My Fair Lady',1964,'7.8',0,'drama','Estados Unidos da América','Filme'),
 ('System Crasher',2019,'7.8',0,'drama','Alemanha','Filme'),
 ('The Game Changers',2019,'7.8',0,'documentary','Estados Unidos da América','Filme'),
 ('Awakenings',1990,'7.8',0,'drama','Estados Unidos da América','Filme'),
 ('Badla',2019,'7.8',0,'thriller','India','Filme'),
 ('Madras Cafe',2013,'7.7',0,'thriller','India','Filme'),
 ('Beasts of No Nation',2015,'7.7',0,'war','Estados Unidos da América','Filme'),
 ('Bonnie and Clyde',1967,'7.7',0,'drama','Estados Unidos da América','Filme'),
 ('Roma',2018,'7.7',0,'drama','México','Filme'),
 ('Kapoor &amp, Sons',2016,'7.7',0,'romance','India','Filme'),
 ('Mucize',2015,'7.7',0,'drama','Turquia','Filme'),
 ('Wind River',2017,'7.7',0,'thriller','França','Filme'),
 ('Oye Lucky! Lucky Oye!',2008,'7.7',0,'comedy','India','Filme'),
 ('Dirty Harry',1971,'7.7',0,'thriller','Estados Unidos da América','Filme'),
 ('Jim &amp, Andy: The Great Beyond - Featuring a Very Special',2017,'7.7',0,'comedy','Estados Unidos da América','Filme'),
 ('Berserk: The Golden Age Arc II - The Battle for Doldrey',2012,'7.7',0,'fantasy','Japão','Filme'),
 ('Silver Linings Playbook',2012,'7.7',0,'drama','Estados Unidos da América','Filme'),
 ('Sanju',2018,'7.7',0,'drama','India','Filme'),
 ('Argo',2012,'7.7',0,'drama','Estados Unidos da América','Filme'),
 ('Guru',2007,'7.7',0,'romance','India','Filme'),
 ('Road to Perdition',2002,'7.7',0,'thriller','Estados Unidos da América','Filme'),
 ('The Trial of the Chicago 7',2020,'7.7',0,'drama','Estados Unidos da América','Filme'),
 ('When Harry Met Sally...',1989,'7.7',0,'romance','Estados Unidos da América','Filme'),
 ('Rock On!!',2008,'7.7',0,'drama','India','Filme'),
 ('In the Family',2017,'7.7',0,'comedy','Turquia','Filme'),
 ('Pyaar Ka Punchnama',2011,'7.7',0,'romance','India','Filme'),
 ('Midnight in Paris',2011,'7.7',0,'fantasy','Estados Unidos da América','Filme'),
 ('Donnie Brasco',1997,'7.7',0,'thriller','Estados Unidos da América','Filme'),
 ('The Blind Side',2009,'7.6',0,'drama','Estados Unidos da América','Filme'),
 ('Sherlock Holmes',2009,'7.6',0,'crime','Reino Unido','Filme'),
 ('Stardust',2007,'7.6',0,'fantasy','Estados Unidos da América','Filme'),
 ('Kuch Kuch Hota Hai',1998,'7.6',0,'drama','India','Filme'),
 ('Parmanu: The Story of Pokhran',2018,'7.6',0,'drama','India','Filme'),
 ('Doctor',2021,'7.6',0,'thriller','India','Filme'),
 ('What Happened',2015,'7.6',0,'musical','Estados Unidos da América','Filme'),
 ('Eddie Murphy Raw',1987,'7.6',0,'comedy','Estados Unidos da América','Filme'),
 ('Delhi Belly',2011,'7.6',0,'comedy','India','Filme'),
 ('The Boy Who Harnessed the Wind',2019,'7.6',0,'drama','Malawi','Filme'),
 ('Kabhi Haan Kabhi Naa',1994,'7.6',0,'comedy','India','Filme'),
 ('The Two Popes',2019,'7.6',0,'drama','Estados Unidos da América','Filme'),
 ('The Social Dilemma',2020,'7.6',0,'drama','Estados Unidos da América','Filme'),
 ('Bad Genius',2017,'7.6',0,'thriller','Tailândia','Filme'),
 ('The Mitchells vs. the Machines',2021,'7.6',0,'animation','Estados Unidos da América','Filme'),
 ('Gifted Hands: The Ben Carson Story',2009,'7.6',0,'drama','Estados Unidos da América','Filme'),
 ('Tell Me Who I Am',2019,'7.6',0,'thriller','Reino Unido','Filme'),
 ('RBG',2018,'7.6',0,'documentary','Estados Unidos da América','Filme'),
 ('Highway',2014,'7.6',0,'drama','India','Filme'),
 ('Athlete A',2020,'7.6',0,'documentary','Estados Unidos da América','Filme'),
 ('Lupin the Third: The Castle of Cagliostro',1979,'7.6',0,'comedy','Japão','Filme'),
 ('Love Actually',2003,'7.6',0,'drama','Reino Unido','Filme'),
 ('Hell or High Water',2016,'7.6',0,'western','Estados Unidos da América','Filme'),
 ('Wake Up Sid',2009,'7.6',0,'comedy','India','Filme'),
 ('Ludo',2020,'7.6',0,'crime','India','Filme'),
 ('Stree',2018,'7.6',0,'horror','India','Filme'),
 ('Aamir',2008,'7.6',0,'thriller','India','Filme'),
 ('I Am Sam',2001,'7.6',0,'drama','Estados Unidos da América','Filme'),
 ('True Grit',2010,'7.6',0,'western','Estados Unidos da América','Filme'),
 ('The Distinguished Citizen',2016,'7.5',0,'comedy','Argentina','Filme'),
 ('Jodhaa Akbar',2008,'7.5',0,'romance','India','Filme'),
 ('The Conjuring',2013,'7.5',0,'thriller','Estados Unidos da América','Filme'),
 ('Dhamaka',2021,'7.5',0,'thriller','India','Filme'),
 ('Bareilly Ki Barfi',2017,'7.5',0,'romance','India','Filme'),
 ('Les MisÃ©rables',2012,'7.5',0,'drama','Reino Unido','Filme'),
 ('Berserk: The Golden Age Arc I - The Egg of the King',2012,'7.5',0,'fantasy','Japão','Filme'),
 ('Dil Se..',1998,'7.5',0,'drama','India','Filme'),
 ('Omar',2013,'7.5',0,'thriller','Território Ocupado Palestino','Filme'),
 ('I Lost My Body',2019,'7.5',0,'fantasy','França','Filme'),
 ('tick',2021,'7.5',0,'drama','Estados Unidos da América','Filme'),
 ('Coming Soon',2014,'7.5',0,'drama','Turquia','Filme'),
 ('Nocturnal Animals',2016,'7.5',0,'drama','Estados Unidos da América','Filme'),
 ('A Monster Calls',2016,'7.5',0,'fantasy','Espanha','Filme'),
 ('On Body and Soul',2017,'7.5',0,'fantasy','Hungria','Filme'),
 ('Ala Vaikunthapurramuloo',2020,'7.5',0,'drama','India','Filme'),
 ('The Devils Advocate',1997,'7.5',0,'horror','Alemanha','Filme'),
 ('Sivaji: The Boss',2007,'7.5',0,'drama','India','Filme'),
 ('Happy as Lazzaro',2018,'7.5',0,'fantasy','Itália','Filme'),
 ('The Guns of Navarone',1961,'7.5',0,'war','Estados Unidos da América','Filme'),
 ('Who Am I',2014,'7.5',0,'thriller','Alemanha','Filme'),
 ('White Christmas',1954,'7.5',0,'romance','Estados Unidos da América','Filme'),
 ('Ip Man 2',2010,'7.5',0,'drama','China','Filme'),
 ('Menace II Society',1993,'7.5',0,'drama','Estados Unidos da América','Filme'),
 ('Hum Aapke Hain Koun..!',1994,'7.5',0,'romance','India','Filme'),
 ('Blow',2001,'7.5',0,'drama','Estados Unidos da América','Filme'),
 ('Begin Again',2013,'7.4',0,'comedy','Estados Unidos da América','Filme'),
 ('Uncut Gems',2019,'7.4',0,'drama','Estados Unidos da América','Filme'),
 ('Sherlock Holmes: A Game of Shadows',2011,'7.4',0,'crime','Estados Unidos da América','Filme'),
 ('Rurouni Kenshin Part I: Origins',2012,'7.4',0,'drama','Japão','Filme'),
 ('Forgotten',2017,'7.4',0,'thriller','República da Coréia','Filme'),
 ('Tamasha',2015,'7.4',0,'drama','India','Filme'),
 ('Mudbound',2017,'7.4',0,'drama','Estados Unidos da América','Filme'),
 ('Lady Bird',2017,'7.4',0,'drama','Estados Unidos da América','Filme'),
 ('Mollys Game',2017,'7.4',0,'drama','Canadá','Filme'),
 ('Raman Raghav 2.0',2016,'7.4',0,'thriller','India','Filme'),
 ('Once Upon a Time in Mumbaai',2010,'7.4',0,'thriller','India','Filme'),
 ('Jaane Tu... Ya Jaane Na',2008,'7.4',0,'drama','India','Filme'),
 ('Peepli Live',2010,'7.4',0,'drama','India','Filme'),
 ('Even the Rain',2010,'7.4',0,'drama','Espanha','Filme'),
 ('Darkest Hour',2017,'7.4',0,'drama','Reino Unido','Filme'),
 ('The Bucket List',2007,'7.4',0,'drama','Estados Unidos da América','Filme'),
 ('American Factory',2019,'7.4',0,'documentary','Estados Unidos da América','Filme'),
 ('Miss Americana',2020,'7.4',0,'documentary','Estados Unidos da América','Filme'),
 ('The Hand of God',2021,'7.4',0,'drama','Itália','Filme'),
 ('A Nightmare on Elm Street',1984,'7.4',0,'horror','Estados Unidos da América','Filme'),
 ('Meenakshi Sundareshwar',2021,'7.4',0,'comedy','India','Filme'),
 ('Kurup',2021,'7.4',0,'crime','India','Filme'),
 ('Crazy',2011,'7.4',0,'romance','Estados Unidos da América','Filme'),
 ('Schumacher',2021,'7.4',0,'sports','Alemanha','Filme'),
 ('Guzaarish',2010,'7.4',0,'drama','India','Filme'),
 ('What the Health',2017,'7.4',0,'documentary','Estados Unidos da América','Filme'),
 ('Mirage',2018,'7.4',0,'thriller','Espanha','Filme'),
 ('Bully',2011,'7.4',0,'drama','Estados Unidos da América','Filme'),
 ('Phantom Thread',2017,'7.4',0,'romance','Estados Unidos da América','Filme'),
 ('Looper',2012,'7.4',0,'thriller','Estados Unidos da América','Filme'),
 ('Felon',2008,'7.4',0,'crime','Estados Unidos da América','Filme'),
 ('Life in a Metro',2007,'7.4',0,'drama','India','Filme'),
 ('Kabhi Khushi Kabhie Gham',2001,'7.4',0,'drama','India','Filme'),
 ('Kaminey',2009,'7.4',0,'drama','India','Filme'),
 ('Girl',1999,'7.3',0,'drama','Estados Unidos da América','Filme'),
 ('Talaash',2012,'7.3',0,'thriller','India','Filme'),
 ('Starship Troopers',1997,'7.3',0,'scifi','Estados Unidos da América','Filme'),
 ('The Guernsey Literary &amp, Potato Peel Pie Society',2018,'7.3',0,'romance','Reino Unido','Filme'),
 ('Okja',2017,'7.3',0,'drama','República da Coréia','Filme'),
 ('Ishqiya',2010,'7.3',0,'comedy','India','Filme'),
 ('The Edge of Seventeen',2016,'7.3',0,'comedy','Estados Unidos da América','Filme'),
 ('Pyaar Ka Punchnama 2',2015,'7.3',0,'comedy','India','Filme'),
 ('The Nightingale',2018,'7.3',0,'thriller','Austrália','Filme'),
 ('Corpse Bride',2005,'7.3',0,'fantasy','Estados Unidos da América','Filme'),
 ('Memoirs of a Geisha',2005,'7.3',0,'drama','França','Filme'),
 ('El Camino: A Breaking Bad Movie',2019,'7.3',0,'thriller','Estados Unidos da América','Filme'),
 ('Official Secrets',2019,'7.3',0,'thriller','Reino Unido','Filme'),
 ('Coach Carter',2005,'7.3',0,'drama','Estados Unidos da América','Filme'),
 ('The King',2019,'7.3',0,'drama','Austrália','Filme'),
 ('Identity',2003,'7.3',0,'thriller','Estados Unidos da América','Filme'),
 ('The Best of Enemies',2019,'7.3',0,'drama','Estados Unidos da América','Filme'),
 ('The Professionals',1966,'7.3',0,'western','Estados Unidos da América','Filme'),
 ('Raat Akeli Hai',2020,'7.3',0,'thriller','India','Filme'),
 ('Little Women',1994,'7.3',0,'drama','Estados Unidos da América','Filme'),
 ('Badhaai Do',2022,'7.3',0,'comedy','India','Filme'),
 ('The Conjuring 2',2016,'7.3',0,'thriller','Estados Unidos da América','Filme'),
 ('The Fundamentals of Caring',2016,'7.3',0,'drama','Estados Unidos da América','Filme'),
 ('The Ballad of Buster Scruggs',2018,'7.3',0,'western','Estados Unidos da América','Filme'),
 ('Shot Caller',2017,'7.3',0,'thriller','Estados Unidos da América','Filme'),
 ('The Disaster Artist',2017,'7.3',0,'comedy','Estados Unidos da América','Filme'),
 ('Blue Jay',2016,'7.3',0,'romance','Estados Unidos da América','Filme'),
 ('Te3n',2016,'7.3',0,'thriller','India','Filme'),
 ('Monster',2003,'7.3',0,'crime','Estados Unidos da América','Filme'),
 ('No One Killed Jessica',2011,'7.2',0,'crime','India','Filme'),
 ('Toilet: A Love Story',2017,'7.2',0,'comedy','India','Filme'),
 ('Wish Dragon',2021,'7.2',0,'fantasy','China','Filme'),
 ('Mom',2017,'7.2',0,'crime','India','Filme'),
 ('The Professor and the Madman',2019,'7.2',0,'thriller','Estados Unidos da América','Filme'),
 ('Kabir Singh',2019,'7.2',0,'drama','India','Filme'),
 ('Dolemite Is My Name',2019,'7.2',0,'comedy','Estados Unidos da América','Filme'),
 ('In the Line of Fire',1993,'7.2',0,'drama','Estados Unidos da América','Filme'),
 ('The Witcher: Nightmare of the Wolf',2021,'7.2',0,'fantasy','Polônia','Filme'),
 ('Ittefaq',2017,'7.2',0,'thriller','India','Filme'),
 ('The Tinder Swindler',2022,'7.2',0,'crime','Reino Unido','Filme'),
 ('First They Killed My Father',2017,'7.2',0,'drama','Camboja','Filme'),
 ('Dont Look Up',2021,'7.2',0,'scifi','Estados Unidos da América','Filme'),
 ('Wazir',2016,'7.2',0,'thriller','India','Filme'),
 ('Gabbar Is Back',2015,'7.2',0,'drama','India','Filme'),
 ('Fyre',2019,'7.2',0,'documentary','Estados Unidos da América','Filme'),
 ('Steve Jobs',2015,'7.2',0,'drama','Reino Unido','Filme'),
 ('Shooter',2007,'7.2',0,'thriller','Estados Unidos da América','Filme'),
 ('The Butler',2013,'7.2',0,'drama','Estados Unidos da América','Filme'),
 ('The Siege of Jadotville',2016,'7.2',0,'thriller','Irlanda','Filme'),
 ('Closer',2004,'7.2',0,'drama','Reino Unido','Filme'),
 ('Private Life',2018,'7.2',0,'drama','Estados Unidos da América','Filme'),
 ('American Murder: The Family Next Door',2020,'7.2',0,'crime','Estados Unidos da América','Filme'),
 ('St. Vincent',2014,'7.2',0,'comedy','Estados Unidos da América','Filme'),
 ('A River Runs Through It',1992,'7.2',0,'drama','Estados Unidos da América','Filme'),
 ('The Patriot',2000,'7.2',0,'drama','Alemanha','Filme'),
 ('Five Feet Apart',2019,'7.2',0,'romance','Estados Unidos da América','Filme'),
 ('Michael Clayton',2007,'7.2',0,'thriller','Estados Unidos da América','Filme'),
 ('The Edge of Democracy',2019,'7.2',0,'documentary','Brasil','Filme'),
 ('Paddington',2014,'7.2',0,'comedy','França','Filme'),
 ('Wedding Association',2013,'7.1',0,'comedy','#N/A','Filme'),
 ('Let Me In',2010,'7.1',0,'horror','Reino Unido','Filme'),
 ('Raajneeti',2010,'7.1',0,'drama','India','Filme'),
 ('Body of Lies',2008,'7.1',0,'drama','Reino Unido','Filme'),
 ('The Forgotten Battle',2020,'7.1',0,'drama','Lituânia','Filme'),
 ('Knock Down the House',2019,'7.1',0,'documentary','Estados Unidos da América','Filme'),
 ('The Call',2020,'7.1',0,'thriller','República da Coréia','Filme'),
 ('Forgetting Sarah Marshall',2008,'7.1',0,'comedy','Estados Unidos da América','Filme'),
 ('The Railway Man',2013,'7.1',0,'drama','Reino Unido','Filme'),
 ('The Great Hack',2019,'7.1',0,'documentary','Estados Unidos da América','Filme'),
 ('Paddleton',2019,'7.1',0,'drama','Estados Unidos da América','Filme'),
 ('Desperado',1995,'7.1',0,'thriller','Estados Unidos da América','Filme'),
 ('Gantz:O',2016,'7.1',0,'animation','Japão','Filme'),
 ('The Ring',2002,'7.1',0,'horror','Japão','Filme'),
 ('Margin Call',2011,'7.1',0,'thriller','Estados Unidos da América','Filme'),
 ('Copenhagen',2014,'7.1',0,'drama','Estados Unidos da América','Filme'),
 ('Black Mirror: Bandersnatch',2018,'7.1',0,'scifi','Reino Unido','Filme'),
 ('Metallica: Through the Never',2013,'7.1',0,'musical','Estados Unidos da América','Filme'),
 ('Seven Years in Tibet',1997,'7.1',0,'drama','Estados Unidos da América','Filme'),
 ('Girl',2018,'7.1',0,'drama','Holanda','Filme'),
 ('Kung Fu Panda 3',2016,'7.1',0,'comedy','Estados Unidos da América','Filme'),
 ('To All the Boys Ive Loved Before',2018,'7.1',0,'romance','Estados Unidos da América','Filme'),
 ('Arthur Christmas',2011,'7.1',0,'drama','Reino Unido','Filme'),
 ('Trailer Park Boys: The Movie',2006,'7.1',0,'comedy','Canadá','Filme'),
 ('Karthik Calling Karthik',2010,'7.1',0,'thriller','India','Filme'),
 ('The White Tiger',2021,'7.1',0,'drama','India','Filme'),
 ('Shootout at Lokhandwala',2007,'7.1',0,'crime','India','Filme'),
 ('The Devil All the Time',2020,'7.1',0,'drama','Estados Unidos da América','Filme'),
 ('Tangerine',2015,'7.1',0,'comedy','Estados Unidos da América','Filme'),
 ('The Danish Girl',2015,'7.1',0,'drama','Alemanha','Filme'),
 ('The Unforgivable',2021,'7.1',0,'drama','Alemanha','Filme'),
 ('Phir Hera Pheri',2006,'7.1',0,'comedy','India','Filme'),
 ('War Dogs',2016,'7.1',0,'crime','Estados Unidos da América','Filme'),
 ('The Dig',2021,'7.1',0,'drama','Reino Unido','Filme'),
 ('Blade',1998,'7.1',0,'action','Estados Unidos da América','Filme'),
 ('Luck by Chance',2009,'7.1',0,'romance','India','Filme'),
 ('Namastey London',2007,'7.1',0,'comedy','India','Filme'),
 ('Don',2006,'7.1',0,'thriller','India','Filme'),
 ('Don 2',2011,'7.1',0,'action','Alemanha','Filme'),
 ('Main Hoon Na',2004,'7',0,'drama','India','Filme'),
 ('Gangubai Kathiawadi',2022,'7',0,'drama','India','Filme'),
 ('Croupier',1998,'7',0,'thriller','França','Filme'),
 ('Pieces of a Woman',2020,'7',0,'drama','Hungria','Filme'),
 ('Raw',2016,'7',0,'horror','Bélgica','Filme'),
 ('Loving',2016,'7',0,'drama','Reino Unido','Filme'),
 ('Harold &amp, Kumar Go to White Castle',2004,'7',0,'comedy','Estados Unidos da América','Filme'),
 ('Haseen Dillruba',2021,'7',0,'drama','India','Filme'),
 ('Rose Island',2020,'7',0,'drama','Itália','Filme'),
 ('Ferry',2021,'7',0,'drama','Holanda','Filme'),
 ('Handsome Devil',2017,'7',0,'drama','Irlanda','Filme'),
 ('Torbaaz',2020,'7',0,'drama','India','Filme'),
 ('Ip Man 3',2015,'7',0,'drama','Hong-Kong','Filme'),
 ('The Foreigner',2017,'7',0,'thriller','India','Filme'),
 ('Mirai',2018,'7',0,'fantasy','Japão','Filme'),
 ('Gaga: Five Foot Two',2017,'7',0,'musical','Estados Unidos da América','Filme'),
 ('The Christmas Chronicles',2018,'7',0,'fantasy','Estados Unidos da América','Filme'),
 ('Sarkar',2018,'7',0,'drama','India','Filme'),
 ('Rambo',2008,'7',0,'thriller','Estados Unidos da América','Filme'),
 ('Dil Dhadakne Do',2015,'7',0,'drama','India','Filme'),
 ('Soul Surfer',2011,'7',0,'drama','Estados Unidos da América','Filme'),
 ('Happy Gilmore',1996,'7',0,'comedy','Estados Unidos da América','Filme'),
 ('Den of Thieves',2018,'7',0,'thriller','Estados Unidos da América','Filme'),
 ('The Zookeepers Wife',2017,'7',0,'drama','Reino Unido','Filme'),
 ('The Platform',2019,'7',0,'horror','Espanha','Filme'),
 ('Public Enemies',2009,'7',0,'crime','Estados Unidos da América','Filme'),
 ('Ip Man 4: The Finale',2019,'7',0,'drama','China','Filme'),
 ('John Q',2002,'7',0,'drama','Estados Unidos da América','Filme'),
 ('Fashion',2008,'6.9',0,'romance','India','Filme'),
 ('Ma Raineys Black Bottom',2020,'6.9',0,'musical','Estados Unidos da América','Filme'),
 ('Any Given Sunday',1999,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('The Long Riders',1980,'6.9',0,'western','Estados Unidos da América','Filme'),
 ('Get on Up',2014,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('Fukrey',2013,'6.9',0,'romance','India','Filme'),
 ('Chup Chup Ke',2006,'6.9',0,'comedy','India','Filme'),
 ('Then Came You',2019,'6.9',0,'comedy','Estados Unidos da América','Filme'),
 ('The Wolfs Call',2019,'6.9',0,'thriller','França','Filme'),
 ('Cloudy with a Chance of Meatballs',2009,'6.9',0,'animation','Estados Unidos da América','Filme'),
 ('Our Souls at Night',2017,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('Chandigarh Kare Aashiqui',2021,'6.9',0,'crime','India','Filme'),
 ('Welcome',2007,'6.9',0,'romance','India','Filme'),
 ('Everybody Knows',2018,'6.9',0,'drama','Itália','Filme'),
 ('The Meyerowitz Stories (New and Selected)',2017,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('I Dont Feel at Home in This World Anymore',2017,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('The Highwaymen',2019,'6.9',0,'thriller','Estados Unidos da América','Filme'),
 ('Legend',2015,'6.9',0,'thriller','Estados Unidos da América','Filme'),
 ('AK vs AK',2020,'6.9',0,'drama','India','Filme'),
 ('My Girl',1991,'6.9',0,'comedy','Estados Unidos da América','Filme'),
 ('Amanda Knox',2016,'6.9',0,'crime','Dinamarca','Filme'),
 ('2 States',2014,'6.9',0,'comedy','India','Filme'),
 ('The Power of the Dog',2021,'6.9',0,'drama','Canadá','Filme'),
 ('The Half of It',2020,'6.9',0,'comedy','Estados Unidos da América','Filme'),
 ('Outlaw King',2018,'6.9',0,'drama','Reino Unido','Filme'),
 ('Mary Kom',2014,'6.9',0,'drama','India','Filme'),
 ('Suffragette',2015,'6.9',0,'drama','França','Filme'),
 ('Legend of the Guardians: The Owls of GaHoole',2010,'6.9',0,'fantasy','Estados Unidos da América','Filme'),
 ('Christine',2016,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('The Night Comes for Us',2018,'6.9',0,'thriller','Indonésia','Filme'),
 ('The Trip',2021,'6.9',0,'comedy','Noruega','Filme'),
 ('The Dirt',2019,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('Top Gun',1986,'6.9',0,'drama','Estados Unidos da América','Filme'),
 ('Radhe Shyam',2022,'6.9',0,'romance','India','Filme'),
 ('Sorry to Bother You',2018,'6.9',0,'fantasy','Estados Unidos da América','Filme');

UPDATE Filme_Series set main_genre = 'documentario' WHERE main_genre = 'documentary';

UPDATE Filme_Series SET main_genre = 'comedia' WHERE main_genre = 'comedy';

UPDATE Filme_Series SET main_genre = 'scifi' WHERE main_genre = 'ficção cientifica';

DELETE FROM Filme_Series WHERE main_genre = 'western';

UPDATE Filme_Series SET main_genre = 'ação ' WHERE main_genre = 'action';

UPDATE Filme_Series SET main_genre = 'fantasia' WHERE main_genre = 'fantasy';

UPDATE Filme_Series SET main_genre = 'guerra' WHERE main_genre = 'war';

DELETE FROM Filme_Series WHERE main_genre = 'guerra';

SELECT * FROM `Filme_Series` WHERE pais ='estados unidos da america';

SELECT * FROM `Filme_Series` WHERE pais ='argentina';

SELECT * FROM Filme_Series WHERE pais = 'estados unidos daamerica' AND Filme_Series = 'serie';